print(my_variable) # make NameError. cause my_veriable isn't define before

# need to traceback error,,,to see where it happend.let's make simple traceback
"""
we can traceback by follow some rools...
1. At the very bottom it gives you the error which is raises and description...
2. What line of your code raised the error...
3. What function that line is in...
4. What function called the function that the line is in..
"""
#what you do , if you have an error...?
"""
1. look at your code line by line, carefully,,,

2. Put the error and message into Google, see if something is comes up with StackOverflow

3. Look at the code you've written again, this time more slowly, and run through it as if
you were a computer.Do you notice anything that could potentially be a source of the error?

4. Run only some part of the code in isolation, that'll help identtify which part of your
code is giving you an error.

5. Use a debugger(we'll learn how in the next couple videos).

6. And of course, ask questions in the Course Q&A. We're here to help!

"""








